### ISSUE TITLE
 ValueError: setting an array element with a sequence. 

### ISSUE THREAD

**Issue by burcia1711** [Stanford-ILIAD/active-preference-based-gpr#1]
Hello,

When running test.py, I get the following error:

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[/content/test.py](https://localhost:8080/#) in <module>
     16 
     17 gp = GaussianProcess(initialPoint, theta, noise_level)
---> 18 gp.updateParameters([[0,0],[1,0]], 1) # We compare the features [0,0] and [1,0], and the former one is preferred
     19 gp.updateParameters([[2,-1],[3,1]],-1) # We compare the features [2,-1] and [3,1], and the latter one is preferred
     20 

1 frames
[/content/GP.py](https://localhost:8080/#) in updateParameters(self, query, answer)
     21         self.K = self.covK()
     22         self.Kinv = inv(self.K+np.identity(2*len(self.listQueries))*1e-8) #adding the 1e-8 for numerical stability
---> 23         self.fqmean = self.meanmode()
     24         self.W = self.hessian()
     25 

[/content/GP.py](https://localhost:8080/#) in meanmode(self)
     47         n = len(self.listQueries)
     48         Kinv = self.Kinv
---> 49         listResults = np.array(self.listQueries)[:,2]
     50         def logposterior(f):
     51             fodd  = f[1::2]

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (1, 3) + inhomogeneous part.

---------------------------------------------------------------------------

What would be the problem and how can i solve this? 

Thanks in advance!

**Comment by ebiyik** [comment]
Thanks for letting us know about this issue. Apparently, our code was not the nicest and I believe the newer versions of Numpy punished us for that. Anyway, I just pushed a commit that resolves this issue. Hope it helps!
